# -*- coding: utf-8 -*-
"""BT01. Tháp Hà Nộiipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/ldthinh220802/cau_truc_du_lieu_va_giai_thuat/blob/main/BT01_Th%C3%A1p_H%C3%A0_N%E1%BB%99iipynb.ipynb
"""

def thapHaNoi(n, toaMot, toaHai, toaBa):
  if n == 1:
	  print("chuyen tu", toaMot, "sang", toaBa)

  else:
	  thapHaNoi(n-1, toaMot, toaBa, toaHai)
	  print("chuyen tu", toaMot, "sang", toaBa)
	  thapHaNoi(n-1, toaHai, toaMot, toaBa)  
   
thapHaNoi(2,"a","b","c")