# -*- coding: utf-8 -*-
"""BT02. Ước số chung lớn nhất.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/ldthinh220802/cau_truc_du_lieu_va_giai_thuat/blob/main/BT02_%C6%AF%E1%BB%9Bc_s%E1%BB%91_chung_l%E1%BB%9Bn_nh%E1%BA%A5t.ipynb
"""

def uscln(a, b):
    if (b == 0):
        return a;
    return uscln(b, a % b);

 


a = int(input("Nhập số nguyên dương a = "));
b = int(input("Nhập số nguyên dương b = "));
print("Ước số chung lớn nhất của", a, "và", b, "là:", uscln(a, b));