# -*- coding: utf-8 -*-
"""BT03. Tính giai thừa của 1 số.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/ldthinh220802/cau_truc_du_lieu_va_giai_thuat/blob/main/BT03_T%C3%ADnh_giai_th%E1%BB%ABa_c%E1%BB%A7a_1_s%E1%BB%91.ipynb
"""

def giaithua(n):
    
    if n == 1: 
       return 1 
    else: 
        return (n * giaithua(n-1))

num = int(input("Nhập số cần tính giai thừa: "))

print("Giai thừa của", num, "là", giaithua(num))