# -*- coding: utf-8 -*-
"""BT07. Cài đặt danh sách liên kết kép.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/ldthinh220802/cau_truc_du_lieu_va_giai_thuat/blob/main/BT07_C%C3%A0i_%C4%91%E1%BA%B7t_danh_s%C3%A1ch_li%C3%AAn_k%E1%BA%BFt_k%C3%A9p.ipynb
"""

# Node of a doubly linked list
class Node:
    def __init__(self, next=None, prev=None, data=None):
        self.next = next # reference to next node in DLL
        self.prev = prev # reference to previous node in DLL
        self.data = data