# -*- coding: utf-8 -*-
"""BT09. Cài đặt hàng đợi - queue.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/ldthinh220802/cau_truc_du_lieu_va_giai_thuat/blob/main/BT09_C%C3%A0i_%C4%91%E1%BA%B7t_h%C3%A0ng_%C4%91%E1%BB%A3i_queue.ipynb
"""

class Queue:

    def __init__(self):
        self.queue = []

    def enqueue(self, item):
        self.queue.append(item)

    def dequeue(self):
        if len(self.queue) < 1:
            return None
        return self.queue.pop(0)

    def size(self):
        return len(self.queue)