# -*- coding: utf-8 -*-
"""BT10 + BT11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/ldthinh220802/cau_truc_du_lieu_va_giai_thuat/blob/main/BT10_%2B_BT11.ipynb
"""

from binarytree import build
values = [7, 3, 2, 6, 9, None, 1, 5, 8]
root = build(values)
print(root)
print(root.preorder) # duyệt cây theo thứ tự trước
print(root.postorder) # duyệt cây theo thứ tự sau