# -*- coding: utf-8 -*-
"""BT12. Cài đặt đồ thị vô hướng

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/ldthinh220802/cau_truc_du_lieu_va_giai_thuat/blob/main/BT12_C%C3%A0i_%C4%91%E1%BA%B7t_%C4%91%E1%BB%93_th%E1%BB%8B_v%C3%B4_h%C6%B0%E1%BB%9Bng.ipynb
"""

import networkx as nx
import matplotlib.pyplot as plt
G = nx.DiGraph()
G.add_edges_from([('A','B'),('B','C'),('B','D'),('D','C')])


# Specify the edges you want here
red_edges = [('A', 'C')]
edge_colours = ['black' if not edge in red_edges else 'red'
                for edge in G.edges()]
black_edges = [edge for edge in G.edges() if edge not in red_edges]
pos = nx.spring_layout(G)
nx.draw_networkx_nodes(G, pos, cmap=plt.get_cmap('jet'), 
                        node_size = 500)
nx.draw_networkx_labels(G, pos)
nx.draw_networkx_edges(G, pos, edgelist=black_edges, arrows=False)
plt.show()